name: monero
description: Monero Dart library.  Uses Rust bound via FFI.  Includes a separate optional commandline interface for building the latest Monero release from source (by default) and/or optionally managing and verifying binary release archives (install with `dart pub global activate monero` and use as in `monero --help`).
version: 0.0.5-dev.2
repository: https://github.com/ManyMath/monerodart

executables:
  monero:

environment:
  sdk: ^3.6.0-0

dependencies:
  ffi: ^2.1.3
  crypto: ^3.0.5
  http: ^1.2.2
  path: ^1.9.0

dev_dependencies:
  ffigen: ^14.0.0
  lints: ^3.0.0
  test: ^1.24.0
