name: monero
description: Monero Dart library.  Uses Rust bound via FFI.  Includes a separate commandline application for managing and verifying Monero binary release archives (install with `dart pub global activate monero` and use as in `monero --help`).
version: 0.0.4
repository: https://github.com/ManyMath/monerodart

executables:
  monero:

environment:
  sdk: ^3.6.0-0

dependencies:
  native_toolchain_rust_mirror: ^0.1.0-dev.8
  native_assets_cli: ^0.7.2
  ffi: ^2.1.3
  ffigen: ^14.0.0
  crypto: ^3.0.5
  http: ^1.2.2
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
